name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/*
jobs:
  build-image:
    uses: making/workflows/.github/workflows/build-docker-image.yaml@main
  save-image:
    needs: build-image
    uses: making/workflows/.github/workflows/save-images.yaml@main